name: Kernel Build CI (Ginkgo - Clang 15)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required by artifact v4

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Set up Environment
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex git libncurses-dev libssl-dev python3 python-is-python3 rsync unzip zip zlib1g-dev

    - name: Download latest LLVM prebuilt
      run: |
        mkdir clang
        curl -L https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.8/LLVM-20.1.8-Linux-X64.tar.xz -o clang.tar.xz
        tar -xf clang.tar.xz -C clang --strip-components=1

    - name: Install GCC 9.4 cross-compiler
      run: |
        sudo apt update
        sudo apt install -y gcc-9-aarch64-linux-gnu g++-9-aarch64-linux-gnu binutils-aarch64-linux-gnu

    - name: Clean AnyKernel3 folder if exists
        run: rm -rf AnyKernel3

    - name: Download AnyKernel3
        run: git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git


    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CC=clang
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export PATH=$PWD/clang/bin:$PATH

        make O=out cuttlefish_defconfig
        make -j$(nproc) O=out \
          CC=clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=$CROSS_COMPILE


